# pytorch_lightning==1.8.1
seed_everything: 42
trainer:
  logger: true
  enable_checkpointing: true
  devices: 1
  enable_progress_bar: true
  max_epochs: 100
  max_steps: -1
  log_every_n_steps: 10
  accelerator: auto
  inference_mode: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
        log_momentum: false
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val/loss
        save_last: true
        save_top_k: 3
model:
  lr: 0.0001
  weight_decay: 0.01
  loss: mse
  vocoder_path: /home/eng000/sgile/models/hifigan/generator_universal.pth.tar
  network: PostNet
  network_kwargs:
    n_mel_channels: 80
    postnet_embedding_dim: 512
    postnet_kernel_size: 5
    postnet_n_convolutions: 5
data:
  data_dir: /space/partner/nrc/work/dt/eng000/Experiments/data/spec-to-spec/EveryVoice/original-output
  train_filelist: /space/partner/nrc/work/dt/eng000/Experiments/data/spec-to-spec/EveryVoice/train.txt
  val_filelist: /space/partner/nrc/work/dt/eng000/Experiments/data/spec-to-spec/EveryVoice/val.txt
  test_filelist: /space/partner/nrc/work/dt/eng000/Experiments/data/spec-to-spec/EveryVoice/test.txt
  sort: false
  split: false
  segment_size: 32
  batch_size: 16
  num_workers: 4
